[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid
silent=false

[program:warp-gateway]
command=dotnet warp.dll
directory=/warp
environment=ASPNETCORE_ENVIRONMENT="Development",ASPNETCORE_URLS="http://0.0.0.0:5000"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=100

[program:dev-api]
command=dotnet warp.apis.developer.dll
directory=/warp
environment=ASPNETCORE_ENVIRONMENT="Development",ASPNETCORE_URLS="http://127.0.0.1:5002"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=200

[program:admin-api]
command=dotnet warp.apis.admin.dll
directory=/warp
environment=ASPNETCORE_ENVIRONMENT="Development",ASPNETCORE_URLS="http://127.0.0.1:5003"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
priority=300

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
