openapi: 3.0.4
info:
  title: 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /admin/health:
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      responses:
        '200':
          description: OK
  /admin/users/count:
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      responses:
        '200':
          description: OK
  /admin/users/pages/count:
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      responses:
        '200':
          description: OK
  '/admin/users/pages/{pageindex}':
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: pageindex
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
  '/admin/users/{email}':
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IUser'
        required: true
      responses:
        '200':
          description: OK
    delete:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  '/admin/users/{email}/permissions':
    get:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      tags:
        - 'warp.apis.admin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          description: OK
components:
  schemas:
    IUser:
      type: object
      properties:
        id:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        permissions:
          type: array
          items:
            type: string
          nullable: true
          readOnly: true
      additionalProperties: false