admin:
  ClusterId: "admin_cluster"
  Match:
    Path: "/admin/{**remainder}"
  Metadata:
    Preprocess:
      $include: middlewares/OpenTelemetryStart.yml
      AdminJwtValidator:
        Type: "Warp.Dilithium.Middleware.JwtValidator, warp.dilithium"
        Options:
          JwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
          ValidEmails:
            - "ani@anionline.me"
      RateLimiter:
        Type: "Warp.Dilithium.Middleware.RateLimiter, warp.dilithium"
        Options:
          RateLimitHz: 2.0
      AdminPermissionsChecker:
        Type: "Warp.Dilithium.Middleware.PermissionsChecker, warp.dilithium"
        Options:
          RequiredPermissions:
            - "admin"
    Postprocess:
      $include: middlewares/OpenTelemetryEnd.yml