developer:
  ClusterId: "developer_api_cluster"
  Match:
    Path: "/developer/{**remainder}"
  Metadata:
    Preprocess:
      $include: middlewares/OpenTelemetryStart.yml
      JwtValidator:
        Type: "Warp.Dilithium.Middleware.JwtValidator, warp.dilithium"
        Options:
          JwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
      RateLimiter:
        Type: "Warp.Dilithium.Middleware.RateLimiter, warp.dilithium"
        Options:
          RateLimitHz: 2.0
      DevPermissionsChecker:
        Type: "Warp.Dilithium.Middleware.PermissionsChecker, warp.dilithium"
        Options:
          RequiredPermissions:
            - "developer"
          CreateUserIfNotFound: true
          DefaultPermissions:
            - "developer"
            - "user"
    Predispatch:
      DevOpenApiValidator:
        Type: "Warp.Dilithium.Middleware.OpenApiValidator, warp.dilithium"
        Options:
          SpecFile: "spec/warp.apis.developer.yml"
    Postprocess:
      $include: middlewares/OpenTelemetryEnd.yml
