services:
  warp:
    build:
      target: dev # Only for devcontainer
    environment:
      - RUN_WARP=false # We don't need these in the devcontainer
      - RUN_PLASMA=false
    volumes:
      - .:/workspace/warp # Mount our workspace folder
    ports:
      - "5004:5004"  # warp.latinum webhook endpoint