services:
  warp:
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ../.env
      - ../.env.local
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ..:/workspace/warp
    working_dir: /workspace/warp
    depends_on:
      - otel-collector
      
      # Uncomment the specific database containers you want to use
      # for development. 
      # By default, warp is configured to use Sqlite
      # which doesn't require a separate container.
      # - postgres
      # - firestore
    networks:
      - warp-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ../otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "8889:8889"  # Prometheus metrics
    depends_on:
      - jaeger
    networks:
      - warp-network

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
    networks:
      - warp-network


  postgres:
    image: postgres:15
    user: "1000:1000"
    environment:
      POSTGRES_DB: warp
      POSTGRES_USER: warp
      POSTGRES_PASSWORD: warp_dev_password
      PGUSER: vscode
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    networks:
      - warp-network

  firestore:
    build:
      context: .
      dockerfile: firestore.Dockerfile
    ports:
      - "8080:8080"  # Firestore emulator UI
      - "4000:4000"  # Firestore Web UI
    networks:
      - warp-network

networks:
  warp-network:
    driver: bridge