# Warp Gateway Configuration
$include: "shared/${DATACONTEXT_IMPL}-datacontext.yml"
$include: "shared/opentelemetry.yml"

ReverseProxy:
  Clusters:
    admin_api_cluster:
      Destinations:
        admin:
          Address: "http://127.0.0.1:5003/"
    developer_api_cluster:
      Destinations:
        developer:
          Address: "http://127.0.0.1:5002/"
    memoryalpha_cluster:
      Destinations:
        memoryalpha:
          Address: "http://memoryalpha-rag-api:8000"
  
  Routes:
    $include: "routes/admin.yml"
    $include: "routes/developer.yml"
    
    $include: "routes/basic/memoryalpha.yml"
    $include: "routes/pro/memoryalpha.yml"

Kestrel:
  Endpoints:
    Public:
      Url: "http://*:5000"

